package Tokenizer;

public enum TokenType{
	IF, ELSE, THEN, VAR, VOID, INT, BOOL, CHAR, WHILE, RETURN, HD, TL, FST, SND, BOOLVALUE, PRINT, ISEMPTY, READ, ID, ROUNDBRACKETOPEN, ROUNDBRACKETCLOSE, CURLYBRACKETOPEN, CURLYBRACKETCLOSE, PLUS, SQUAREBRACKETCLOSE, MULTIPLY, DIVIDE, MODULO, SEMICOLON, COMMA, ERROR, INTVALUE, SQUAREBRACKETOPEN, MINUS, BIGGER, SMALLER, ARROW, EMPTYLIST, DOUBLESEMICOLON, EQUALS, SMALLEREQUALS, INEQUALS, BIGGEREQUALS, OR, AND, ASSIGNMENT, DOUBLECOLON, COLON, MULTI,

}
